version: "2"
services:
  transmission:
    image: lsioarmhf/transmission
    container_name: transmission
    mem_limit: 100m
    volumes:
      - /home/seedbox/Transmission/Config:/config
      - /home/seedbox/Transmission/Downloads:/downloads
      - /home/seedbox/Transmission/Watch:/watch
    env_file:
      - /home/seedbox/user.env
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped

  jackett:
    image: lsioarmhf/jackett
    container_name: jackett
    mem_limit: 120m
    volumes:
      - /home/seedbox/Jackett/Config:/config
      - /home/seedbox/Transmission/Watch:/downloads
    env_file:
      - /home/seedbox/user.env
    ports:
      - "9117:9117"
    restart: unless-stopped

  muximux:
    image: lsioarmhf/muximux
    container_name: muximux
    # mem_limit: 100m
    volumes:
      - /home/seedbox/Muximux/Config:/config
    env_file:
      - /home/seedbox/user.env
    ports:
      - "81:80"
    restart: unless-stopped

  sonarr:
    image: lsioarmhf/sonarr
    container_name: sonarr
    mem_limit: 200m
    volumes:
      - /home/seedbox/Sonarr/Config:/config
      - /home/seedbox/Sonarr/Library:/tv
      - /home/seedbox/Transmission/Downloads:/downloads
    env_file:
      - /home/seedbox/user.env
    ports:
      - "8989:8989"
    restart: unless-stopped
    links:
      - transmission
      - jackett

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    mem_limit: 120m
    volumes:
      - /home/seedbox/Bazarr/Config:/config
      - /home/seedbox/Bazarr/TV:/tv
      - /home/seedbox/Bazarr/Movies:/movies
    env_file:
      - /home/seedbox/user.env
    ports:
      - "6767:6767"
    restart: unless-stopped
    links:
      - sonarr
